/**
 * Builds @box-ui/tokens from the Figma Variables dumps.
 *
 *   tokens/figma/*.txt  ->  dist/css/*.css + dist/index.js + dist/index.d.ts + dist/tokens.json
 *
 * The Figma variable graph is preserved 1:1: every alias becomes a `var()`
 * reference, so switching a mode on `<html>` re-resolves the whole chain
 * exactly the way switching a mode does in Figma.
 *
 *   primitives            (single "Value" mode, raw literals)
 *     ^-- Color   [data-accent]  Blue Sky Teal Emerald Orange Amber Violet Purple Cyan Yellow
 *          ^-- Mode    [data-theme]   Light Dark
 *     ^-- Rounding[data-radius]  Low Medium High
 *          ^-- Grid    [data-device]  Desktop Mobile
 *     ^-- Typography [data-font]  Inter, Inter Display, Inter Tight, Inter Variable
 *          ^-- Grid    [data-device]
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseDumps } from './parse-figma.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const pkg = join(here, '..');
const repo = join(pkg, '..', '..');
const dist = join(pkg, 'dist');

const PREFIX = '--box';

/**
 * How each collection is rendered.
 *   varPrefix — inserted between `--box-` and the slugified variable path
 *   strip     — leading path segment removed before slugifying
 *   switch    — the HTML attribute that selects a mode, plus its default mode
 */
const LAYERS = {
  palette: { varPrefix: 'color', label: 'Color Palette', group: 'primitive' },
  spacing: { label: 'Spacing', group: 'primitive' },
  rounding: { label: 'Rounding', group: 'primitive' },
  size: { label: 'Size', group: 'primitive' },
  opacity: { label: 'Opacity', group: 'primitive' },
  'type-scale': { label: 'Typography', group: 'primitive' },

  font: { varPrefix: 'type', label: 'Typography', group: 'semantic', switch: { attr: 'data-font', default: 'Inter' } },
  radius: { varPrefix: 'radius', strip: 'rounding', label: 'Rounding', group: 'semantic', switch: { attr: 'data-radius', default: 'Medium' } },
  accent: { label: 'Color', group: 'semantic', switch: { attr: 'data-accent', default: 'Blue' } },
  mode: { label: 'Mode', group: 'semantic', switch: { attr: 'data-theme', default: 'Light' } },
  grid: { label: 'Grid', group: 'semantic', switch: { attr: 'data-device', default: 'Desktop' } },
};

/** Where an `@alias` of a given collection is looked up, in order. */
const ALIAS_SCOPE = {
  accent: ['palette'],
  mode: ['accent'],
  radius: ['rounding'],
  font: ['type-scale'],
  grid: ['font', 'radius', 'spacing', 'size'],
};

/** Emission order — later layers override earlier ones in the cascade. */
const ORDER = ['palette', 'spacing', 'rounding', 'size', 'opacity', 'type-scale', 'font', 'radius', 'accent', 'mode', 'grid'];

/** Figma spells the strongest rounding mode "Hight"; `high` is the canonical slug. */
const MODE_SLUG = { Hight: 'high' };
const MODE_SLUG_ALIASES = { Hight: ['hight'] };

const UNITLESS = /^font-weight\//;
const RATIO = /^opacity\//;

const slug = (s) =>
  s
    .toLowerCase()
    .replace(/[\s/]+/g, '-')
    .replace(/[^a-z0-9-]/g, '')
    .replace(/-+/g, '-');

const modeSlug = (m) => MODE_SLUG[m] ?? slug(m);

// ---------------------------------------------------------------------------

const collections = parseDumps(join(repo, 'tokens', 'figma'));
const byId = Object.fromEntries(collections.map((c) => [c.id, c]));

function varName(collectionId, path) {
  const layer = LAYERS[collectionId];
  const cleaned = layer.strip ? path.replace(new RegExp(`^${layer.strip}/`), '') : path;
  return [PREFIX, layer.varPrefix, slug(cleaned)].filter(Boolean).join('-');
}

function resolveAlias(collectionId, ref) {
  for (const target of ALIAS_SCOPE[collectionId] ?? []) {
    if (byId[target]?.variables[ref]) return varName(target, ref);
  }
  throw new Error(`Unresolved alias "@${ref}" in collection "${collectionId}"`);
}

function literal(collectionId, path, value) {
  switch (value.type) {
    case 'color':
      return value.value;
    case 'string':
      return `"${value.value}", var(${PREFIX}-font-fallback)`;
    case 'number':
      if (RATIO.test(path)) return String(value.value / 100);
      if (UNITLESS.test(path)) return String(value.value);
      return `${value.value}px`;
    default:
      throw new Error(`Unsupported value type ${value.type}`);
  }
}

function declaration(collectionId, path, value) {
  const v = value.type === 'alias' ? `var(${resolveAlias(collectionId, value.ref)})` : literal(collectionId, path, value);
  return `  ${varName(collectionId, path)}: ${v};`;
}

function block(selectors, lines) {
  return `${selectors.join(',\n')} {\n${lines.join('\n')}\n}\n`;
}

// --- CSS ---------------------------------------------------------------------

const header = (title) =>
  `/* ${title}\n * Generated by packages/tokens/scripts/build.mjs from tokens/figma/*.txt.\n * Do not edit by hand — edit the Figma Variables and re-run \`npm run build -w @box-ui/tokens\`.\n */\n\n`;

const primitiveCss = [header('Box UI — primitive tokens (Box UI | Primitives)')];
const primitiveLines = [`  ${PREFIX}-font-fallback: system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;`];

for (const id of ORDER) {
  const c = byId[id];
  if (LAYERS[id].group !== 'primitive') continue;
  primitiveLines.push(`\n  /* ${c.figmaName} */`);
  for (const [path, v] of Object.entries(c.variables)) {
    primitiveLines.push(declaration(id, path, v.values[c.modes[0]]));
  }
}
primitiveCss.push(block([':root'], primitiveLines));

const themeCss = [header('Box UI — semantic tokens, one block per Figma mode')];
const adaptive = [header('Box UI — automatic mode selection (opt-in via adaptive.css)')];

for (const id of ORDER) {
  const c = byId[id];
  const layer = LAYERS[id];
  if (layer.group !== 'semantic') continue;

  themeCss.push(`/* ${c.figmaName} — [${layer.switch.attr}] */\n`);

  for (const mode of c.modes) {
    const lines = Object.entries(c.variables).map(([path, v]) => declaration(id, path, v.values[mode]));
    const selectors = [`[${layer.switch.attr}="${modeSlug(mode)}"]`];
    for (const alias of MODE_SLUG_ALIASES[mode] ?? []) selectors.push(`[${layer.switch.attr}="${alias}"]`);
    if (mode === layer.switch.default) selectors.unshift(':root');
    themeCss.push(block(selectors, lines));
  }
}

// prefers-color-scheme + viewport width pick a mode when the author has not.
{
  const dark = byId.mode;
  const darkLines = Object.entries(dark.variables).map(([p, v]) => declaration('mode', p, v.values.Dark));
  adaptive.push(
    `@media (prefers-color-scheme: dark) {\n${block([`  :root:not([data-theme="light"])`], darkLines.map((l) => `  ${l}`))}}\n`,
  );

  const grid = byId.grid;
  const mobileLines = Object.entries(grid.variables).map(([p, v]) => declaration('grid', p, v.values.Mobile));
  adaptive.push(
    `@media (max-width: 767px) {\n${block([`  :root:not([data-device="desktop"])`], mobileLines.map((l) => `  ${l}`))}}\n`,
  );
}

const indexCss = `${header('Box UI — all tokens')}@import "./primitives.css";\n@import "./theme.css";\n`;

// --- JS / TS -----------------------------------------------------------------

const model = {
  $source: {
    primitives: 'https://www.figma.com/design/gbgGmuUBQ7sIfL256KaDXX/Box-UI--Primitives',
    tokens: 'https://www.figma.com/design/ccLFzQtw3AuTuHWoHYf2dS/Box-UI--Tokens',
    icons: 'https://www.figma.com/design/9pupgeWag4Ssc7jdAYvXMt/Box-UI--Icons',
  },
  collections: {},
};

for (const id of ORDER) {
  const c = byId[id];
  model.collections[id] = {
    figmaName: c.figmaName,
    group: LAYERS[id].group,
    attribute: LAYERS[id].switch?.attr ?? null,
    defaultMode: LAYERS[id].switch ? modeSlug(LAYERS[id].switch.default) : null,
    modes: c.modes.map((m) => ({ name: m, slug: modeSlug(m) })),
    variables: Object.entries(c.variables).map(([path, v]) => ({
      path,
      cssVar: varName(id, path),
      values: Object.fromEntries(
        c.modes.map((m) => {
          const value = v.values[m];
          return [
            modeSlug(m),
            value.type === 'alias'
              ? { alias: value.ref, cssVar: resolveAlias(id, value.ref) }
              : { value: value.type === 'color' ? value.value : value.value },
          ];
        }),
      ),
    })),
  };
}

const modeLists = Object.fromEntries(
  Object.entries(model.collections)
    .filter(([, c]) => c.attribute)
    .map(([id, c]) => [id, c.modes.map((m) => m.slug)]),
);

/** `background/base/primary` -> `tokens.background.base.primary` */
function nest(id) {
  const tree = {};
  for (const v of model.collections[id].variables) {
    const parts = (LAYERS[id].strip ? v.path.replace(new RegExp(`^${LAYERS[id].strip}/`), '') : v.path).split('/');
    let node = tree;
    parts.forEach((part, i) => {
      const key = part.toLowerCase().replace(/[^a-z0-9]+/g, '-');
      if (i === parts.length - 1) node[key] = `var(${v.cssVar})`;
      else node = node[key] ??= {};
    });
  }
  return tree;
}

const js = `${header('Box UI — token API')}export const modes = ${JSON.stringify(modeLists, null, 2)};

export const attributes = ${JSON.stringify(
  Object.fromEntries(Object.entries(model.collections).filter(([, c]) => c.attribute).map(([id, c]) => [id, c.attribute])),
  null,
  2,
)};

export const defaults = ${JSON.stringify(
  Object.fromEntries(Object.entries(model.collections).filter(([, c]) => c.attribute).map(([id, c]) => [id, c.defaultMode])),
  null,
  2,
)};

/** Semantic tokens, as ready-to-use \`var()\` references. */
export const color = ${JSON.stringify(nest('mode'), null, 2)};
export const accent = ${JSON.stringify(nest('accent'), null, 2)};
export const layout = ${JSON.stringify(nest('grid'), null, 2)};
export const radius = ${JSON.stringify(nest('radius'), null, 2)};
export const typeface = ${JSON.stringify(nest('font'), null, 2)};

/** The full Figma variable graph, for documentation and tooling. */
export { default as model } from './model.js';
`;

const dts = `${header('Box UI — token API')}export declare const modes: {
${Object.entries(modeLists)
  .map(([k, v]) => `  ${k}: ${v.map((m) => `"${m}"`).join(' | ')}[];`)
  .join('\n')}
};
${Object.entries(modeLists)
  .map(([k, v]) => `export type ${k[0].toUpperCase()}${k.slice(1)}Mode = ${v.map((m) => `"${m}"`).join(' | ')};`)
  .join('\n')}

export declare const attributes: Record<string, string>;
export declare const defaults: Record<string, string>;

type TokenTree = { [key: string]: string | TokenTree };
export declare const color: TokenTree;
export declare const accent: TokenTree;
export declare const layout: TokenTree;
export declare const radius: TokenTree;
export declare const typeface: TokenTree;

export interface TokenVariable {
  path: string;
  cssVar: string;
  values: Record<string, { value?: string | number; alias?: string; cssVar?: string }>;
}
export interface TokenCollection {
  figmaName: string;
  group: 'primitive' | 'semantic';
  attribute: string | null;
  defaultMode: string | null;
  modes: { name: string; slug: string }[];
  variables: TokenVariable[];
}
export declare const model: { $source: Record<string, string>; collections: Record<string, TokenCollection> };
`;

// --- write -------------------------------------------------------------------

mkdirSync(join(dist, 'css'), { recursive: true });
writeFileSync(join(dist, 'css', 'primitives.css'), primitiveCss.join(''));
writeFileSync(join(dist, 'css', 'theme.css'), themeCss.join(''));
writeFileSync(join(dist, 'css', 'adaptive.css'), adaptive.join(''));
writeFileSync(join(dist, 'css', 'index.css'), indexCss);
writeFileSync(join(dist, 'tokens.json'), `${JSON.stringify(model, null, 2)}\n`);
writeFileSync(join(dist, 'model.js'), `${header('Box UI — Figma variable graph')}export default ${JSON.stringify(model, null, 2)};\n`);
writeFileSync(join(dist, 'index.js'), js);
writeFileSync(join(dist, 'index.d.ts'), dts);

const counts = ORDER.map((id) => `${byId[id].figmaName} (${id}): ${Object.keys(byId[id].variables).length} vars × ${byId[id].modes.length} mode(s)`);
console.log(`@box-ui/tokens built\n  ${counts.join('\n  ')}`);
