/**
 * Builds @box-ui/icons.
 *
 * The Figma file `Box UI | Icons` carries the UI Icons set as 1253 component
 * sets × 6 `Style` variants (Bold, Bold Duotone, Broken, Line Duotone, Linear,
 * Outline) — that set is Solar by 480 Design. This script takes the geometry
 * from the canonical Solar distribution (`@iconify-json/solar`, CC BY 4.0),
 * splits it per style and emits:
 *
 *   src/data/<style>.json   { "<icon>": "<svg body>" }   — one file per Figma Style mode
 *   src/catalog.json        { styles, categories, icons } — the gallery index
 *
 * Every icon is 24×24 and paints with `currentColor`, so it inherits
 * `--box-content-*` like any other Box UI surface.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const pkg = join(here, '..');

/** Figma `Style` variant -> Solar file suffix. Order matches the Figma variant order. */
export const STYLES = [
  { slug: 'bold', figma: 'Bold', suffix: '-bold' },
  { slug: 'bold-duotone', figma: 'Bold Duotone', suffix: '-bold-duotone' },
  { slug: 'broken', figma: 'Broken', suffix: '-broken' },
  { slug: 'line-duotone', figma: 'Line Duotone', suffix: '-line-duotone' },
  { slug: 'linear', figma: 'Linear', suffix: '-linear' },
  { slug: 'outline', figma: 'Outline', suffix: '-outline' },
];

// Longest suffix first so `-bold-duotone` is never mistaken for `-bold`.
const MATCHERS = [...STYLES].sort((a, b) => b.suffix.length - a.suffix.length);

const iconSet = require('@iconify-json/solar/icons.json');
const metadata = require('@iconify-json/solar/metadata.json');
const info = require('@iconify-json/solar/info.json');

/** Resolve iconify aliases down to a concrete body. */
function bodyOf(name, seen = new Set()) {
  if (iconSet.icons[name]) return iconSet.icons[name].hidden ? null : iconSet.icons[name].body;
  const alias = iconSet.aliases?.[name];
  if (!alias || seen.has(name)) return null;
  seen.add(name);
  return bodyOf(alias.parent, seen);
}

export function split(name) {
  for (const style of MATCHERS) {
    if (name.endsWith(style.suffix)) return { base: name.slice(0, -style.suffix.length), style: style.slug };
  }
  return null;
}

/**
 * Reads the Solar distribution and writes the per-style payloads.
 *
 * Guarded so the module can be imported for `STYLES` and `split()` without
 * rebuilding anything as a side effect — a test that regenerates the fixtures
 * it is checking proves nothing.
 */
export function build() {
  /** Suffixed Solar name -> Solar category, from the set metadata. */
  const categoryOf = {};
  for (const [category, names] of Object.entries(metadata.categories ?? {})) {
    for (const name of names) {
      const parsed = split(name);
      if (parsed) categoryOf[parsed.base] ??= category;
    }
  }

  const data = Object.fromEntries(STYLES.map((s) => [s.slug, {}]));
  const icons = new Map();

  for (const name of [...Object.keys(iconSet.icons), ...Object.keys(iconSet.aliases ?? {})]) {
    const parsed = split(name);
    if (!parsed) continue;
    const body = bodyOf(name);
    if (!body) continue;

    data[parsed.style][parsed.base] = body;
    const entry = icons.get(parsed.base) ?? {
      name: parsed.base,
      category: categoryOf[parsed.base] ?? 'Other',
      styles: [],
    };
    entry.styles.push(parsed.style);
    icons.set(parsed.base, entry);
  }

  const catalog = {
    source: {
      set: info.name,
      author: info.author.name,
      authorUrl: info.author.url,
      license: info.license.title,
      licenseUrl: info.license.url,
      figma: 'https://www.figma.com/design/9pupgeWag4Ssc7jdAYvXMt/Box-UI--Icons',
    },
    viewBox: `0 0 ${iconSet.width ?? 24} ${iconSet.height ?? 24}`,
    styles: STYLES.map(({ slug, figma }) => ({ slug, figma })),
    categories: [...new Set([...icons.values()].map((i) => i.category))].sort(),
    icons: [...icons.values()]
      .map((i) => ({ ...i, styles: STYLES.filter((s) => i.styles.includes(s.slug)).map((s) => s.slug) }))
      .sort((a, b) => a.name.localeCompare(b.name)),
  };

  mkdirSync(join(pkg, 'src', 'data'), { recursive: true });
  for (const style of STYLES) {
    writeFileSync(join(pkg, 'src', 'data', `${style.slug}.json`), `${JSON.stringify(data[style.slug])}\n`);
  }
  writeFileSync(join(pkg, 'src', 'catalog.json'), `${JSON.stringify(catalog, null, 2)}\n`);

  // Named exports keep `import { ArrowUp } from '@box-ui/icons/names'` honest in TS.
  const names = catalog.icons.map((i) => i.name);
  writeFileSync(
    join(pkg, 'src', 'names.ts'),
    `// Generated by scripts/build.mjs — do not edit.\nexport type IconName =\n${names.map((n) => `  | '${n}'`).join('\n')};\n\nexport const iconNames: IconName[] = ${JSON.stringify(names)};\n`,
  );

  const perStyle = STYLES.map((s) => `${s.figma}: ${Object.keys(data[s.slug]).length}`).join(', ');
  console.log(
    `@box-ui/icons built\n  ${catalog.icons.length} icons in ${catalog.categories.length} categories\n  ${perStyle}`,
  );

  // Figma family catalogues (Flags / Payments / Brands) travel with the package
  // but have no geometry until `npm run icons:figma` is run — see README.
  const families = JSON.parse(readFileSync(join(pkg, 'src', 'figma-families.json'), 'utf8'));
  console.log(
    `  families: ${Object.entries(families.families)
      .map(([k, v]) => `${k} ${v.items.length}`)
      .join(', ')}`,
  );
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) build();
